export default {
  GET_USER_SUCCESS: 'GET_USER_SUCCESS',
  INCREMENT: 'INCREMENT',
  GET_MY_ALL_FILES_SUCCES: 'GET_MY_ALL_FILES_SUCCES',
  POST_LOGIN_SUCCES: 'POST_LOGIN_SUCCES',
  POST_CHECK_LOGIN_SUCCES: 'POST_CHECK_LOGIN_SUCCES',
  LOGOUT_SUCCES: 'LOGOUT_SUCCES',
  ADD_USER_SUCCES: 'ADD_USER_SUCCES',
}